### ISSUE TITLE
Disconnected from room at 1:30 when answer via CallKit and device remains locked

### ISSUE THREAD

**Issue by jeffpoulton** [twilio/twilio-video-ios#29] opened 2018-11-08 18:28 UTC
### Description

When answering an incoming call via CallKit, if the user does not unlock the device after accepting the call, the call will drop after 1:30 (one minute and thirty seconds). 

### Preconditions
* Ensure Device B has a device passcode enabled.

### Steps to Reproduce

1. Run an instances of VideoCallKitQuickStart on two devices
2. On Device A, join the designated room (e.g. Room 5)
3. On Device B, use the "Simulate Incoming Call" button and enter the same room as in step 2.
4. On Device B, before the incoming call is received, lock the device
5. On Device B, answer the incoming call without unlocking the device
6. On Device A, confirm that Device B has joined the room
7. Wait for ~1:30

#### Code

n/a - it happens in the stock VideoCallKitQuickStart.

#### Expected Behavior

Device B should not be dropped from the room.

#### Actual Behavior

* Device B disconnected from the room as observed from another device that is active in the room. (See screenshot A)
* On Device B, the iOS CallKit screen continues to show the call as active (See Screenshot B), giving the user no visual indication that the call has dropped.
* At 2:00 mark, an error message from Device B is printed to the console (see the Log section below) and when the phone is unlocked, the error message is displayed in the app (See Screenshot C)

#### Reproduces How Often

* 100% of the time across several different apps.
* Reproducible on the VideoCallKitQuickStart build
* Reproducible on two of the apps we build

#### Logs

No log entries are entered at 1:30, but at 2:00, the following entries appear in the console:

```2018-11-08 10:46:14.993972-0700 VideoCallKitQuickStart[1582:625390] Unsubscribed from audio track for Participant Roger
2018-11-08 10:46:14.994528-0700 VideoCallKitQuickStart[1582:625390] Unsubscribed from video track for Participant Roger
2018-11-08 10:46:15.087347-0700 VideoCallKitQuickStart[1582:625390] Disconncted from room MFI-1584, error = Optional(Error Domain=com.twilio.video Code=53000 "Signaling connection error" UserInfo={NSLocalizedDescription=Signaling connection error, NSLocalizedFailureReason=Unable to re-establish signaling connection to Twilio})
2018-11-08 10:46:15.099656-0700 VideoCallKitQuickStart[1582:625473] [avas] AVAudioSessionPortImpl.mm:56:ValidateRequiredFields: Unknown selected data source for Port Speaker (type: Speaker)
2018-11-08 10:46:15.101739-0700 VideoCallKitQuickStart[1582:625473] [avas] AVAudioSessionPortImpl.mm:56:ValidateRequiredFields: Unknown selected data source for Port Speaker (type: Speaker)
2018-11-08 10:46:15.102163-0700 VideoCallKitQuickStart[1582:625473] [avas] AVAudioSessionPortImpl.mm:56:ValidateRequiredFields: Unknown selected data source for Port Speaker (type: Speaker)
```

#### Video iOS SDK

2.5.3 via Cocoapods (also tested back to 1.3.10)

#### Xcode

9.3
10.0

#### iOS Version

11.3
12.0
12.1

#### iOS Device

iPhone X
iPhone 6s
iPhone 8

![screenshot a](https://user-images.githubusercontent.com/19457/48219083-cbbb4b80-e348-11e8-8ccd-7ede1064274c.jpeg)
![screenshot b](https://user-images.githubusercontent.com/19457/48219084-cc53e200-e348-11e8-9ac6-18b151ef4b4c.jpeg)
![screenshot c](https://user-images.githubusercontent.com/19457/48219086-cc53e200-e348-11e8-90b5-9b67b3222ff2.jpeg)

**Comment by paynerc** [comment] 2018-11-09 15:21
Good morning, @jeffpoulton,

I am trying to reproduce this issue but as of yet, have been unsuccessful. I am following the steps you have listed:

* Device A, an iPhone 6Plus joins a room sharing audio and video.
* Device B, an iPhone X, is set to join via the CallKit notification. I then lock the phone.
* When the CallKit notification triggers, I answer the call.
* I have both devices connected to the room and I hear audio flowing back and forth between the devices.

Both devices have now been in the same room for over 10 minutes and I have not been able to reproduce the issue. I have attempted it numerous times this morning and am not able to make it happen. Am I missing a step? I am using the latest Swift VideoCallKitQuickStart code, running against `2.5.3`. I think we are going to need some further info to attempt to diagnose this. If you wouldn't mind, collect a RoomSid from an example where this occurred and send an email to support@twilio.com. In that message, include the RoomSid and a note that states that you are working with me and I asked you to send that along. From there I can start digging to see if I see anything related to the networking connection.

You did show that you received a signaling connection error. That leads me to believe something fishy is happening on the network side. Are you on WiFi or Cellular when this issue occurs? When you make the connection, are you hearing audio flowing for the first 1:30 before it disconnects?

I do think that there should be something that we can do to alert that CallKit UI that the call has been disconnected. That would be a betterment for at least providing feedback to the user that this situation occurred. But we also need to get to the root cause of what you are experiencing.

Looking forward to hearing back from you,

Ryan

**Comment by paynerc** [comment] 2018-11-09 15:53
@jeffpoulton,

Also, another thing. Can you enable debug logging in the app and send that to support as well? You can do this by placing the following in your `application(application:, didFinishLaunchingWithOptions launchOptions:)` delegate method:

```
import TwilioVideo

....

func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        TwilioVideo.setLogLevel(.debug)
        return true
    }
```

This would help us diagnose what is happening with your signaling connection.

Thank you!

Ryan

**Comment by paynerc** [comment] 2018-11-09 17:37
@jeffpoulton,

I created an internal ticket to update the sample code to raise the disconnection error to the CallKit framework so the user gets notified. We will get that updated soon.

Also, when you do send the logs and RoomSid to the support email, drop a note here that you have done that as well so I know look for it.

Thanks again!

Ryan

**Comment by paynerc** [comment] 2018-11-12 16:56
@jeffpoulton,

Just wanted to let you know that we added better handling for when the call is disconnected due to an error (https://github.com/twilio/video-quickstart-swift/pull/327).

Ryan

**Comment by paynerc** [comment] 2018-11-13 17:12
@jeffpoulton,

Just checking in to see if you have had a chance to collect that debugging information and sent it over in a support email?

Ryan

**Comment by jeffpoulton** [comment] 2018-11-13 20:58
@paynerc Sorry for the radio silence. I wasn't getting notifications of your comments and just checked in to see if there was any activity. 

As for not being able to replicate, are you ensuring that Device B remains locked upon answering the incoming call? That is the key step with this issue; otherwise, if Device B gets unlocked upon answering, the call does not disconnect. 

I will do a new build with the debugger and provide the RoomSid via the support email.

**Comment by paynerc** [comment] 2018-11-13 21:00
@jeffpoulton,

No worries about the silence. Just  was making sure you weren't being blocked by this. Yes, I have not touched the phone other than to answer the CallKit call. I had a call go on for 45 minutes and it never dropped.

Leet me know when you send the RoomSid and I will look for it in the system and we can go from there. Also, check out the latest example. We are better handling when the call is disconnected from the remote side.

Ryan

**Comment by jeffpoulton** [comment] 2018-11-13 21:29
RoomSid and debug log have been sent to the support email address.

**Comment by jeffpoulton** [comment] 2018-11-13 21:36
@paynerc I'm emailing a 2nd log file that was generated from an instancing that includes your bug fix in twilio/video-quickstart-swift#327.

**Comment by paynerc** [comment] 2018-11-13 21:55
@jeffpoulton,

Thank you for sending this. I have begun to dig though this and will let you know what I come up with.

Ryan

**Comment by paynerc** [comment] 2018-11-14 17:04
@jeffpoulton,

Thank you for sending this. I have begun to dig though this and will let you know what I come up with.

Ryan

**Comment by spacedema** [comment] 2018-11-19 11:03
I have the same issue. At 1:28-1:30 caller device get notified that receiver device has left the room. Receiver device is locked all the time. (Call answered from standard CallKit screen)

If receiver device get unlocked - everything is fine, so maybe receiver device not sending heartbeat if device is locked? (Heartbeat timeout = 88 sec)

**Comment by piyushtank** [comment] 2018-11-20 06:50
@jeffpoulton  Thanks for reporting the issues and providing logs. 
@spacedema Thanks for reporting the issues.

Yes, I am able to reproduce the problem. What you have reported is a bug in Video SDK in group room scenario.

The Video SDK terminates the signaling connections upon creating the SDP answer for the offer received from the room signaling server, and while applying the answer, media engine (webrtc) stops the previously started the audio device, and then it starts again for the new offer. When media engine stops the audio device, if the app is in background, SDK thinks the app is going to be background suspended and and it terminates the signaling connections. And Video SDK misses to re-establish the signaling connection when it's media engine starts the audio device.

I have filed a bug ISDK-2269 for internal tracking. We are working on fixing this bug and release the fix in a few days. 

Thanks again for reporting the bug and helping us out in debugging the problem.

**Comment by spacedema** [comment] 2018-11-20 07:09
@piyushtank Thanks for the answer!

**Comment by jeffpoulton** [comment] 2018-11-27 17:18
@piyushtank thank you for the update and for the quick turnaround!

**Comment by piyushtank** [comment] 2018-12-05 22:47
@jeffpoulton @spacedema We have just released TwilioVideo 2.5.6. It has the fix for the bug you have reported. [Here](https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-2x#256-december-5-2018) are the changelogs.

Please try it out and let me know if you run into any issue.

Thanks again for helping us in debugging the problem.

**Comment by spacedema** [comment] 2018-12-06 08:42
Everything is ok after update to 2.5.6
Many thanks!

**Comment by piyushtank** [comment] 2018-12-11 17:11
Thanks @spacedema for trying it out.

@jeffpoulton , @spacedema - I am closing this ticket as the bug is fixed but feel free to re-open if you observe the issue.

**Closed as completed by piyushtank** 2018-12-11 17:11 UTC
Labels: bug
