### ISSUE TITLE
Mac Catalyst Support

### ISSUE THREAD

**Issue by ozgymlabs** [twilio/twilio-video-ios#121] opened 2020-08-17 01:46 UTC
### Description

Cant build project with twilio iOS sdk since the dylib was built for iOS Simulator

```
building for Mac Catalyst, but linking in dylib built for iOS Simulator, file '/Users/orenzitoun/Github/UP-IOS/Pods/TwilioVideo/Build/iOS/TwilioVideo.framework/TwilioVideo' for architecture x86_64
```

### Steps to Reproduce

1. Try to build your project with the Mac deployment option

#### Expected Behavior

Project should be able to build for Mac Catalyst  

#### Actual Behavior

I'm getting a build error
```
building for Mac Catalyst, but linking in dylib built for iOS Simulator, file '/Users/orenzitoun/Github/UP-IOS/Pods/TwilioVideo/Build/iOS/TwilioVideo.framework/TwilioVideo' for architecture x86_64
```

#### Reproduces How Often

100%

### Versions

TwilioVideo (3.6.1)

#### Video iOS SDK

TwilioVideo (3.6.1)

#### Xcode

Version 12.0 beta 4 (12A8179i)
macOS BigSur 11.0 Beta (20A5343i) 

#### iOS Version

N/A

#### iOS Device

N/A

**Comment by ceaglest** [comment] 2020-08-17 16:59
Dupe of https://github.com/twilio/twilio-video-ios/issues/49.

**Closed as completed by ceaglest** 2020-08-17 16:59 UTC
