### ISSUE TITLE
Bluetooth audio through CallKit stops after device goes to sleep

### ISSUE THREAD

**Issue by jocelynlih** [twilio/twilio-video-ios#19] opened 2018-07-18 22:55 UTC
### Description

Bluetooth audio through CallKit stops after device goes to sleep

### Steps to Reproduce

1. Device 1 is using bluetooth headphones, lock the screen to make sure the call is answered through CallKit
2. Device 2 calls Device 1. Call connects as expected. On Device 1's CallKit screen, it should show the audio is going through bluetooth headphones. 
3. Let Device 1 go to sleep or simply lock the screen, notice audio is lost on both Device 1 and Device 2

#### Code

Use the CallKit demo code from 

https://github.com/twilio/video-quickstart-swift/blob/master/VideoCallKitQuickStart/ViewController%2BCallKit.swift

#### Expected Behavior

The audio should not be lost. 

#### Actual Behavior

audio is lost. When Device 1 is active again, the audio will work again.

#### Reproduces How Often

100%

#### Logs

```
// Log output when the issue occurs
```

### Versions

2.1.0
2.2.1

#### Video iOS SDK

2.1.0
2.2.1

#### Xcode

9.4

#### iOS Version

iOS 11

#### iOS Device

all devices.

**Comment by jocelynlih** [comment] 2018-07-19 19:44
so we are able to identify the root cause in `TVIDefaultAudioDevice.h` file, line 62-64
```
if (![session setPreferredSampleRate:sampleRate error:&error]) {
        NSLog(@"AVAudioSession setPreferredSampleRate %@",error);
}
```

By commenting out above code, we can no longer reproduce this issue. We are still doing testing to see the side effect of this change, meanwhile, can we get some insight on the purpose of setting preferred sample rate for audio session?

**Comment by ceaglest** [comment] 2018-07-19 19:56
Hi @jocelynlih,

Thanks for letting us know about this issue. We set a preferred sample rate because the default audio device functions most reliably at 48 kHz. In some cases it can get confused and allocate incorrectly sized audio buffers in some sample rate / IO buffer duration combinations and drop audio entirely.

```.objc
if (![session setPreferredSampleRate:sampleRate error:&error]) {
        NSLog(@"AVAudioSession setPreferredSampleRate %@",error);
}
```

I'm glad to hear that this change solves your immediate problem. I'm going to let our audio expert @piyushtank chime in with more information.

Best,
Chris

**Comment by jocelynlih** [comment] 2018-07-19 23:12
Updated finding: so the fix we had only works when it's caller device with bluetooth headphones and we are still having lost audio issue with bluetooth headphones if receiving an incoming call through CallKit and lock the screen. 
I've updated the steps to reproduce it in the issue. Hope to hear from you soon. Thx.

**Comment by piyushtank** [comment] 2018-07-23 02:48
@jocelynlih I tried to reproduce the problem using our `VideoCallKitQuickStart` application on iPhone 6 running iOS 11, and iPhone 7S Plus running iOS 12 Beta3. But I am not able to reproduce the problem. 

Here is what I tried - 

1. User Bob is already connected to a Room.
2. User Alice is running `VideoCallKitQuickStart` on iPhone.  Alice's phone's audio is routed to a Bluetooth device.
3. After launching the app, Alice clicks on `Simulate Incoming Call` button, provides the Room name where Bob is already connected to and enters 10 seconds to simulate an incoming call. 
4. Alice locks the screen. And waits for 10 seconds.
5. After 10 seconds, the incoming call gets simulated and CallKit UI is presented on the locked screen to answer the call. 
6. Alice answers the call using Bluetooth audio device, call audio gets routed to the Bluetooth audio device. Bob and Lice both can hear each other.

7. Alice locks the screen. Alice keeps it in lock screen for about 30 seconds. Bob and Alice can each other. Alice unlocks the screen, Bob and Alice can hear each other very well. Tried phone lock <-> unlock a few times, I did not observe the audio problem. Alice was able communicate audio with Bob via Bluetooth device.

Also, for step #7 above, I allowed the phone to go to sleep by itself after 30 second but audio worked as expected when phone screen was black.

I have following questions / requests for you:
1. Is it possible for you to try our `VideoCallKitQuickStart` and reproduce the scenario ?
2. How are you setting up the audio device ? See [this](https://github.com/twilio/video-quickstart-swift/blob/master/VideoCallKitQuickStart/ViewController.swift#L29) for how `VideoCallKitQuickStart` sets it up.
3. In your test case, at signaling, who connects to the Room first (Device 1 or Device 2) ?
4. Is it possible to enable following logs and share with us?
```        
TwilioVideo.setLogLevel(TVILogLevel.debug)
```

I am sure we will be able to get the bottom of this problem together.

Best,
Piyush

**Comment by jocelynlih** [comment] 2018-07-23 16:47
@piyushtank Hi thank you for getting back to me. 
So I figured out the root cause. 
The original code we used to route audio is 
```swift
let audioDevice = TVIDefaultAudioDevice(block: {
            kDefaultAVAudioSessionConfigurationBlock()            
            do {
                try audioSession.setMode(AVAudioSessionModeVoiceChat)
                try audioSession.overrideOutputAudioPort(.none)
            } catch {
                print(error)
            }
        })

audioDevice.block()
```

Now we rewrite the audio device block to use `AVAudioSessionModeVoiceChat` directly. 

```swift
try session.setCategory(AVAudioSessionCategoryPlayAndRecord, mode: AVAudioSessionModeVoiceChat, options: .allowBluetooth)

```

The bluetooth device is working fine now.

**Comment by piyushtank** [comment] 2018-07-23 17:40
@jocelynlih Awesome. Yes, VoIP call requires `AVAudioSessionCategoryPlayAndRecord` category to be set on `AVAudioSession` with the mode and options set. 

I am closing this ticket as the problem is resolved but feel free to reach out to us if you run into any issues.

**Closed as completed by piyushtank** 2018-07-23 17:40 UTC

**Comment by raphaelrk** [comment] 2020-05-04 01:34
Was having issues with audio on my calls until I set audio playback mode to `AVAudioSessionCategoryPlayAndRecord`. Might be good to have a note of that somewhere.
