### ISSUE TITLE
Unable to connect to room RoomSignalingImpl: State transition failure: kDisconnecting -> kConnecting

### ISSUE THREAD

**Issue by kuldeeptripthee** [twilio/twilio-video-ios#106] opened 2020-06-02 05:02 UTC
### Description

Unable to connect to the room with the token

### Steps to Reproduce

1.  initialise video and audio local track  
2. connect with the ConnectOptions using token

#### Code

```swift

        let connectOptions = ConnectOptions(token: self.token) { (builder) in
            builder.roomName = self.roomID
            if let audioTrack = self.localAudioTrack {
                builder.audioTracks = [ audioTrack ]
            }else{
                builder.audioTracks = [ LocalAudioTrack]()
            }
            if let videoTrack = self.localVideoTrack {
                builder.videoTracks = [ videoTrack ]
            }else{
                builder.videoTracks = [LocalVideoTrack]()
            }
            
        }
         room = TwilioVideoSDK.connect(options: connectOptions, delegate: self)
```

#### Expected Behavior
Should be able to connect to the room
#### Actual Behavior
Not able to connect getting RoomSignalingImpl: State transition failure: kDisconnecting -> kConnecting
#### Reproduces How Often
Always
```.swift
TwilioVideoSDK.setLogLevel(.debug)
```

```
2020-06-02 09:44:36.563080+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): API Call create
2020-06-02 09:44:36.563587+0530 AvidViewsTwilio[379:15852] INFO:Twilio:[Core](0x101656bc0): Creating peer connection signaling thread ...
2020-06-02 09:44:36.565154+0530 AvidViewsTwilio[379:15852] INFO:Twilio:[Core](0x101656bc0): Creating peer connection worker thread ...
2020-06-02 09:44:36.565518+0530 AvidViewsTwilio[379:15852] INFO:Twilio:[Core](0x101656bc0): Creating peer connection networking thread ...
2020-06-02 09:44:36.567150+0530 AvidViewsTwilio[379:15852] INFO:Twilio:[Core](0x101656bc0): Creating peer connection factory ...
2020-06-02 09:44:36.593000+0530 AvidViewsTwilio[379:15852] INFO:Twilio:[Core](0x101656bc0): Done creating peer connection factory.
2020-06-02 09:44:36.593480+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): Done creating AudioMediaFactoryImpl.
2020-06-02 09:44:36.594106+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): API Call createDataTrack
2020-06-02 09:44:36.594528+0530 AvidViewsTwilio[379:15852] INFO:Twilio:[Core](0x101656bc0): Creating a data track ...
2020-06-02 09:44:36.599395+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): API Call createAudioSource
2020-06-02 09:44:36.599730+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): API Call createAudioSource
2020-06-02 09:44:36.601386+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): API Call createAudioTrack
2020-06-02 09:44:36.601714+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): API Call createAudioTrack
2020-06-02 09:44:36.602054+0530 AvidViewsTwilio[379:15852] INFO:Twilio:[Core](0x101656bc0): Adding audio track ...
2020-06-02 09:44:36.607281+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): API Call getSignalingThread
2020-06-02 09:44:36.607628+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): API Call getSignalingThread
2020-06-02 09:44:36.608091+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): API Call getWorkerThread
2020-06-02 09:44:36.608406+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): API Call getWorkerThread
2020-06-02 09:44:36.609161+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): API Call createVideoTrack
2020-06-02 09:44:36.609483+0530 AvidViewsTwilio[379:15852] INFO:Twilio:[Core](0x101656bc0): Creating a video track ...
2020-06-02 09:44:36.659681+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Platform](0x101656bc0): Start capturing with device: <AVCaptureFigVideoDevice: 0x105c61b00 [Front Camera][com.apple.avfoundation.avcapturedevice.built-in_video:1]> format: <<TVIVideoFormat: 0x280022400> size: {640, 480}, fps: 30, format: 420f>.
2020-06-02 09:44:36.667071+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Platform](0x101656bc0): Prepare for capturing.
2020-06-02 09:44:36.670202+0530 AvidViewsTwilio[379:15852] INFO:Twilio:[Platform](0x101656bc0): Starting capture pipeline ...
2020-06-02 09:44:36.727738+0530 AvidViewsTwilio[379:15925] DEBUG:Twilio:[Platform](0x16ec5b000): Adding device input: <AVCaptureDeviceInput: 0x28005f8c0 [Front Camera]>
2020-06-02 09:44:36.745658+0530 AvidViewsTwilio[379:15925] INFO:Twilio:[Platform](0x16ec5b000): Best device format was: <AVCaptureDeviceFormat: 0x28026d410 'vide'/'420f'  640x 480, { 2- 60 fps}, fov:54.400, max zoom:60.00 (upscales @2.00), ISO:34.0-2176.0, SS:0.000013-0.500000, supports HDR>
2020-06-02 09:44:36.891750+0530 AvidViewsTwilio[379:15852] Unknown class _TtC11TwilioVideo9VideoView in Interface Builder file.
2020-06-02 09:44:36.943781+0530 AvidViewsTwilio[379:16155] DEBUG:Twilio:[Platform](0x16f02f000): Video pipeline will start running.
2020-06-02 09:44:36.980096+0530 AvidViewsTwilio[379:16155] DEBUG:Twilio:[Platform](0x16f02f000): Video device will start running: <AVCaptureFigVideoDevice: 0x105c61b00 [Front Camera][com.apple.avfoundation.avcapturedevice.built-in_video:1]>.
2020-06-02 09:44:37.026718+0530 AvidViewsTwilio[379:15852] Metal API Validation Enabled
2020-06-02 09:44:37.234489+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): API Call getWebRtcTrack
2020-06-02 09:44:37.234876+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): API Call getWebRtcTrack
2020-06-02 09:44:37.241255+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Platform](0x101656bc0): Did move to window with size: {375, 667}.
Metal content scale factor is now: 2.000
2020-06-02 09:44:37.252362+0530 AvidViewsTwilio[379:15925] INFO:Twilio:[Platform](0x16ec5b000): ... Finished starting capture.
2020-06-02 09:44:37.252843+0530 AvidViewsTwilio[379:15925] INFO:Twilio:[Platform](0x16ec5b000): AVCaptureSession started running
2020-06-02 09:44:37.264121+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Platform](0x101656bc0): Preparing renderer for frame size: {640, 480}, view bounds: {{46, 0}, {243, 324}}
2020-06-02 09:44:37.264921+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Platform](0x101656bc0): Detected a pixel format change. Preparing the rendering pipeline. Old = none, New = 420f
2020-06-02 09:44:42.142399+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): API Call connect
2020-06-02 09:44:42.142759+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): Creating dedicated notifier queue ...
2020-06-02 09:44:42.150139+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): RoomSignalingImpl::RoomSignalingImpl()
2020-06-02 09:44:42.152651+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): Opening connection a2583538-35f3-46f9-8905-ee79b102442a to wss://global.vss.twilio.com/signaling.
2020-06-02 09:44:42.154218+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): API Call getTrackId
2020-06-02 09:44:42.154538+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): API Call getTrackId
2020-06-02 09:44:42.155015+0530 AvidViewsTwilio[379:15922] DEBUG:Twilio:[Core](0x16eab7000): API Call getTrackId
2020-06-02 09:44:42.155250+0530 AvidViewsTwilio[379:15922] DEBUG:Twilio:[Core](0x16eab7000): API Call getTrackId
2020-06-02 09:44:42.155501+0530 AvidViewsTwilio[379:15922] DEBUG:Twilio:[Core](0x16eab7000): API Call getName
2020-06-02 09:44:42.155701+0530 AvidViewsTwilio[379:15922] DEBUG:Twilio:[Core](0x16eab7000): API Call isEnabled
2020-06-02 09:44:42.159088+0530 AvidViewsTwilio[379:16195] DEBUG:Twilio:[Core](0x16f0bb000): Initialize connection a2583538-35f3-46f9-8905-ee79b102442a.
2020-06-02 09:44:42.160979+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): API Call getWebRtcTrack
2020-06-02 09:44:42.172754+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): API Call getWebRtcTrack
2020-06-02 09:44:42.173208+0530 AvidViewsTwilio[379:15922] DEBUG:Twilio:[Core](0x16eab7000): API Call getTrackId
2020-06-02 09:44:42.173414+0530 AvidViewsTwilio[379:15922] DEBUG:Twilio:[Core](0x16eab7000): API Call getTrackId
2020-06-02 09:44:42.173677+0530 AvidViewsTwilio[379:15922] DEBUG:Twilio:[Core](0x16eab7000): API Call getName
2020-06-02 09:44:42.173870+0530 AvidViewsTwilio[379:15922] DEBUG:Twilio:[Core](0x16eab7000): API Call isEnabled
2020-06-02 09:44:42.176086+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): RoomSignalingImpl: State transition successful: kInit -> kDisconnecting
2020-06-02 09:44:42.193660+0530 AvidViewsTwilio[379:16195] INFO:Twilio:[Core](0x16f0bb000): Will connect to host global.vss.twilio.com.
2020-06-02 09:44:42.377609+0530 AvidViewsTwilio[379:16195] DEBUG:Twilio:[Core](0x16f0bb000): Resolved host global.vss.twilio.com.
2020-06-02 09:44:42.378190+0530 AvidViewsTwilio[379:16195] DEBUG:Twilio:[Core](0x16f0bb000): Connecting to 2406:da1a:149:8600:f839:6a10:43e0:e2bf...
2020-06-02 09:44:42.447541+0530 AvidViewsTwilio[379:16195] DEBUG:Twilio:[Core](0x16f0bb000): Connected to 2406:da1a:149:8600:f839:6a10:43e0:e2bf.
2020-06-02 09:44:42.449360+0530 AvidViewsTwilio[379:16195] DEBUG:Twilio:[Core](0x16f0bb000): Established a TCP connection with 2406:da1a:149:8600:f839:6a10:43e0:e2bf.
2020-06-02 09:44:42.618646+0530 AvidViewsTwilio[379:16195] DEBUG:Twilio:[Core](0x16f0bb000): Completed a TLS handshake with 2406:da1a:149:8600:f839:6a10:43e0:e2bf.
2020-06-02 09:44:42.621347+0530 AvidViewsTwilio[379:16195] DEBUG:Twilio:[Core](0x16f0bb000): Sending WebSocket handshake:
GET /signaling HTTP/1.1

Host: global.vss.twilio.com

Upgrade: websocket

Connection: upgrade

Sec-WebSocket-Key: 4pF+kX/iAQdExy/cXgFUmg==

Sec-WebSocket-Version: 13

Sec-WebSocket-Extensions: permessage-deflate; server_max_window_bits=15; client_max_window_bits=15

User-Agent: Boost.Beast/277 twilio-video-cpp/5.3.0
2020-06-02 09:44:42.703673+0530 AvidViewsTwilio[379:16195] DEBUG:Twilio:[Core](0x16f0bb000): Received WebSocket response:
HTTP/1.1 101 Switching Protocols

Date: Tue, 02 Jun 2020 04:14:42 GMT

Connection: upgrade

Sec-WebSocket-Extensions: permessage-deflate

Sec-WebSocket-Accept: vPKHAYcQ9sn6xYysXUYJ8y3xXps=

Upgrade: WebSocket
2020-06-02 09:44:42.707647+0530 AvidViewsTwilio[379:16195] INFO:Twilio:[Core](0x16f0bb000): Completed WebSocket handshake with 2406:da1a:149:8600:f839:6a10:43e0:e2bf.
2020-06-02 09:44:42.710772+0530 AvidViewsTwilio[379:16195] DEBUG:Twilio:[Core](0x16f0bb000): Sending message (88 bytes):
{"id":"a2583538-35f3-46f9-8905-ee79b102442a","timeout":5000,"type":"hello","version":2}
2020-06-02 09:44:42.791026+0530 AvidViewsTwilio[379:16195] DEBUG:Twilio:[Core](0x16f0bb000): Received message:
{"negotiatedTimeout":5000,"type":"welcome"}
2020-06-02 09:44:42.792058+0530 AvidViewsTwilio[379:16195] DEBUG:Twilio:[Core](0x16f0bb000): Connection a2583538-35f3-46f9-8905-ee79b102442a is ready.
2020-06-02 09:44:43.640409+0530 AvidViewsTwilio[379:16155] DEBUG:Twilio:[Core](0x16f02f000): Parsing 'video' endpoint config: {"video":{"network_traversal_service":{"ttl":14400,"date_created":"Tue, 02 Jun 2020 04:14:43 +0000","date_updated":"Tue, 02 Jun 2020 04:14:43 +0000","capability_token":"video","ice_servers":[{"urls":"turn:global.turn.twilio.com:3478?transport=udp","username":"b25657b4bae883f0802ac1ed456c895cffe439e5e6ef8766242d8493bcbe47a3","credential":"eE0ndjPOPrnwbNB22zK3JiyzieZdDcV/dgq6U+kTjP8="},{"urls":"turns:global.turn.twilio.com:443?transport=tcp","username":"b25657b4bae883f0802ac1ed456c895cffe439e5e6ef8766242d8493bcbe47a3","credential":"eE0ndjPOPrnwbNB22zK3JiyzieZdDcV/dgq6U+kTjP8="}]}}}
2020-06-02 09:44:45.178324+0530 AvidViewsTwilio[379:15922] DEBUG:Twilio:[Core](0x16eab7000): RoomSignalingImpl: State transition failure: kDisconnecting -> kConnecting
2020-06-02 09:44:45.178787+0530 AvidViewsTwilio[379:15922] DEBUG:Twilio:[Core](0x16eab7000): Disconnecting from .
2020-06-02 09:44:45.179149+0530 AvidViewsTwilio[379:15922] DEBUG:Twilio:[Core](0x16eab7000): Closed all Peer Connections
2020-06-02 09:44:45.179446+0530 AvidViewsTwilio[379:15922] DEBUG:Twilio:[Core](0x16eab7000): Canceling disconnect timer.
2020-06-02 09:44:45.180211+0530 AvidViewsTwilio[379:16195] DEBUG:Twilio:[Core](0x16f0bb000): Closing connection a2583538-35f3-46f9-8905-ee79b102442a.
2020-06-02 09:44:45.180641+0530 AvidViewsTwilio[379:16195] DEBUG:Twilio:[Core](0x16f0bb000): Sending message (15 bytes):
{"type":"bye"}
2020-06-02 09:44:45.181456+0530 AvidViewsTwilio[379:16195] DEBUG:Twilio:[Core](0x16f0bb000): Closing the WebSocket by request.
2020-06-02 09:44:45.185294+0530 AvidViewsTwilio[379:16195] DEBUG:Twilio:[Core](0x16f0bb000): Queuing a close request without done.
2020-06-02 09:44:45.311447+0530 AvidViewsTwilio[379:16195] DEBUG:Twilio:[Core](0x16f0bb000): Receive completed, the Client closed the WebSocket.
2020-06-02 09:44:45.312258+0530 AvidViewsTwilio[379:16195] INFO:Twilio:[Core](0x16f0bb000): Connection a2583538-35f3-46f9-8905-ee79b102442a was closed with reason: local category: system message: Operation canceled.
2020-06-02 09:44:45.312990+0530 AvidViewsTwilio[379:16195] DEBUG:Twilio:[Core](0x16f0bb000): The final message send is complete.
2020-06-02 09:44:45.317604+0530 AvidViewsTwilio[379:15922] DEBUG:Twilio:[Core](0x16eab7000): RoomSignalingImpl: State transition successful: kDisconnecting -> kDisconnected
2020-06-02 09:44:45.318292+0530 AvidViewsTwilio[379:15922] DEBUG:Twilio:[Core](0x16eab7000): Invoking cancelled closure.
2020-06-02 09:44:45.318587+0530 AvidViewsTwilio[379:15922] DEBUG:Twilio:[Core](0x16eab7000): Invoking cancelled closure.
2020-06-02 09:44:45.318923+0530 AvidViewsTwilio[379:15922] DEBUG:Twilio:[Core](0x16eab7000): Invoking cancelled closure.
2020-06-02 09:44:45.319660+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): RoomSignalingImpl::~RoomSignalingImpl()
2020-06-02 09:44:45.320077+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): RoomSignalingImpl: State Transition Failure: kDisconnected -> kDisconnecting
```

### Versions
All relevant version information for the issue.

#### Video iOS SDK
3.3

#### Xcode
11.4.1
#### iOS Version
12.4.4.

#### iOS Device
iPhone 6

**Comment by ceaglest** [comment] 2020-06-02 17:15
Hi @kuldeeptripthee,

Thanks for filling an issue. Based on your logs the SDK could contact Twilio's Servers and I would have expected it to continue to connect to the Room after opening a WebSocket. However, I noticed that pretty early on (before the WebSocket was open) the SDK started to disconnect.

> 2020-06-02 09:44:42.142399+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): API Call connect
2020-06-02 09:44:42.176086+0530 AvidViewsTwilio[379:15852] DEBUG:Twilio:[Core](0x101656bc0): RoomSignalingImpl: State transition successful: kInit -> kDisconnecting

There is no record of you calling disconnect so I think it may have been due to the `room` object going out of scope. I can't think of another reason why a locally initiated disconnect would have started.

> room = TwilioVideoSDK.connect(options: connectOptions, delegate: self)

Some questions to diagnose / reproduce the problem:

1. Are you keeping a reference to `room` after calling connect? 
2. Is the issue reproducible in our QuickStart apps as well?

Thanks,
Chris

**Comment by ceaglest** [comment] 2020-06-02 18:22
Hey @kuldeeptripthee,

We tried letting the TVIRoom go out of scope after calling `TwilioVideoSDK.connect()` and experienced very similar log results as you. Can you please double check that you are holding on to `room` for the lifetime that you want to remain connected to it?

Best,
Chris

**Comment by kuldeeptripthee** [comment] 2020-06-03 04:10
Hey @ceaglest,

Thanks for the prompt response.

Yes it was the issue with the room instance scope, fixed it by holding room instance.
Suggest you to keep the room  as shared instance in next versions if possible. This will avoid such kind of mistakes.

Best,
Kuldeep

**Comment by paynerc** [comment] 2020-06-03 13:30
@kuldeeptripthee,

In these example apps, the view controller holds the instance, and the view controller is presented the entire duration of the call. You can also take a look at the [Twilio Video Collaboration App](https://github.com/twilio/twilio-video-app-ios). This is designed as a more realistic video application whereas the Quickstarts are designed to show concepts quickly.

I'm glad you got this issue resolved. 

Ryan

**Closed as completed by paynerc** 2020-06-03 13:30 UTC
Labels: help wanted
