### ISSUE TITLE
TVIVideoView pixelation effect on preview video

### ISSUE THREAD

**Issue by KurasovAnton** [twilio/twilio-video-ios#159] opened 2021-01-08 16:28 UTC
### Description

After migration from v3.7.1 to v4.0.1 I faced the pixelation issue on displaying the preview video(it was implemented following the guidelines https://www.twilio.com/docs/video/ios-getting-started#display-a-camera-preview) 

Precondition:
            TVIVideoView used to render the TVILocalVideoTrack
            Same TVILocalVideoTrack was published to TVIRoom TVILocalParticipant
            TVIVideoView.contentMode = scaleAspectFill;
            TVIVideoView.mirror = true;

#### Expected Behavior

The video is without pixelation effect

#### Actual Behavior

The video is with pixelation effect

#### Reproduces How Often

Each time

#### Video iOS SDK

4.0.1

#### Xcode

Version 12.3

#### iOS devices and version

iPhone 6, iOS 12.4.8
iPhone 11Pro Max, iOS 14.3

This is in reference to ticket # 5622993 created in Twilio support

SDK 4.0.1 with pixelation effect
![image](https://user-images.githubusercontent.com/18266976/104038973-7310c300-51de-11eb-8031-9630d7ae4a6b.png)

SDK 3.6.1 without pixelation effect
![image](https://user-images.githubusercontent.com/18266976/104039564-36919700-51df-11eb-938b-e31ca550eb59.png)

**Comment by piyushtank** [comment] 2021-01-12 05:20
Hi Anton,

Thanks for reporting the bug. 

I am able to reproduce the problem locally. It's a regression added by a renderer fix we released in Version SDK version 4.0.1 where the native scale factor was not applied to the drawable size. We are working on fixing the problem. And, we should be able to ship the fix very quickly - in a next few days. In the meantime, you can use our 4.0.0 SDK where you should not see this problem. 

I apologize for the inconvenience caused by this.

Best,
Piyush

**Comment by KurasovAnton** [comment] 2021-01-14 15:08
Hi Piyush,

Thank you for such a fast response.

I'll give you the response as soon as we update the Twilio SDK to 4.1.0.(Approximately in 2 weeks)

Best Regards,
Anton

**Comment by piyushtank** [comment] 2021-01-14 17:28
Yes, 4.1.0 has the fix for this issue. [Here](https://www.twilio.com/docs/video/changelog-twilio-video-ios-latest#410-january-13-2020) are the changelogs.

**Comment by ceaglest** [comment] 2021-08-20 18:03
I hope the update to 4.1.0+ went as expected, thanks for reporting this bug.

**Closed as completed by ceaglest** 2021-08-20 18:03 UTC
Labels: bug
