### ISSUE TITLE
Opponent video displaying when I connect room.

### ISSUE THREAD

**Issue by mouli457** [twilio/twilio-video-ios#118] opened 2020-07-22 14:42 UTC
Opponent video is displaying automatically when i enter room.I want to call   setupRemoteVideoView() and self.showRoomUI(inRoom: true) methods when opponent click connect.

     func renderRemoteParticipant(participant : RemoteParticipant) -> Bool {
        // This example renders the first subscribed RemoteVideoTrack from the RemoteParticipant.
        let videoPublications = participant.remoteVideoTracks
        for publication in videoPublications {
            if let subscribedVideoTrack = publication.remoteTrack,
                publication.isTrackSubscribed {
               setupRemoteVideoView()
                self.showRoomUI(inRoom: true)
                subscribedVideoTrack.addRenderer(self.remoteView!)
                self.remoteParticipant = participant
                return true
            }
        }
        
        return false
    }

    func renderRemoteParticipants(participants : Array<RemoteParticipant>) {
        for participant in participants {
            // Find the first renderable track.
            if participant.remoteVideoTracks.count > 0,
                renderRemoteParticipant(participant: participant) {
                break
            }
        }
    }

**Comment by paynerc** [comment] 2020-07-24 13:42
This is a duplicate of https://github.com/twilio/video-quickstart-ios/issues/530. Closing this issue in favor of that one as @ceaglest has already responded to that one.

**Closed as completed by paynerc** 2020-07-24 13:42 UTC
