### ISSUE TITLE
App hangs in `-[TVICameraCapturePipeline applicationWillEnterForeground]`

### ISSUE THREAD

**Issue by nsillik** [twilio/twilio-video-ios#21] opened 2018-07-24 17:04 UTC
### Description

When an app which has an open video connection, is put in the background, and re-launched from a notification the app hangs at `-[TVICameraCapturePipeline applicationWillEnterForeground]`.

### Steps to Reproduce

1. Launch application
2. Get into a video session with another user
3. Background app
4. Get a remote notification
5. Tap on remote notification, attempting to launch back into video
6. Hangs

#### Code
I haven't yet put together a small amount of code which reproduces the issue. I can work on that if helpful, it'll be tricky because of the reliance on notifications however.

#### Expected Behavior

The video starts as expected

#### Actual Behavior

Hangs

#### Reproduces How Often

>90%

#### Logs

No twilio related logs are generated on the foregrounding. Here's the only obvious Twilio logging I've seen (but this is generated during the initial successful video connection after the app launches):
```
2018-07-24 09:46:54.483726-0700 Mado - Debug[1670:899447] ERROR:TwilioVideo:[Platform]:AVAudioSession setPreferredInputNumberOfChannels Error Domain=NSOSStatusErrorDomain Code=-50 "(null)"
```

#### Video iOS SDK

TwilioVideo (2.2.1) from Cocoapids

#### Xcode
9.4.1

#### iOS Version

11.2.5

#### iOS Device

iPad Pro (12.9-inch, 2nd generation) (Model A1670)

**Comment by ceaglest** [comment] 2018-07-24 20:03
Hi @nsillik,

Thanks for reporting this issue, and for the detailed description of the problem.

> I haven't yet put together a small amount of code which reproduces the issue. I can work on that if helpful, it'll be tricky because of the reliance on notifications however.

I wonder if it would be possible to reproduce this with a UILocalNotification as well? As you said, I'm not sure if the push notification code would be easy to share.

> 11.2.5
> iPad Pro (12.9-inch, 2nd generation) (Model A1670)

Is it also reproducible on other device models, and OS versions (like iOS 11.4.1)?

Best,
Chris

**Comment by nsillik** [comment] 2018-07-24 20:07
> I wonder if it would be possible to reproduce this with a UILocalNotification as well? As you said, I'm not sure if the push notification code would be easy to share.

Actually, our notification's are silent, so the displayed notification center notification *is* actually a LocalNotfication. Here's the code, it's pretty boring:

```
    if let notificationContent = alert.notificationContent {
      let request = UNNotificationRequest(identifier: alert.id, content: notificationContent, trigger: nil)
      UNUserNotificationCenter.current().add(request, withCompletionHandler: nil)
    }
```

We also aren't doing anything different on being launched from a notification as compared to just being launched from the home screen.

> Is it also reproducible on other device models, and OS versions (like iOS 11.4.1)?

I'm not sure, I'll keep testing and let you know.

**Comment by nsillik** [comment] 2018-07-24 20:26
An update: I reproduced this on an iPhone X running iOS 11.4.1

**Comment by piyushtank** [comment] 2019-07-16 03:14
Hello,

I apologize for the late response. We have done major changes in our Camera APIs in our latest 2.10.0 and 3.0.0-beta releases. The new camera source APIs were originally added in 2.6.0 previews.

With our latest SDK, I tried followed the step with our CallKitQuickStart example but I could not reproduce the problem where app hangs. Similarly, I tried to reproduce the problem with local notification but I could not reproduce the issue.

Based on above  test results, and recent updates on our SDK, I am moving ahead and closing the ticket. Please feel free to open the ticket if you are running into the issue again.

Best,
Piyush

**Closed as completed** 2019-07-16 03:14 UTC
