### ISSUE TITLE
providerDidReset call Every time

### ISSUE THREAD

**Issue by AhmadDurrani579** [twilio/twilio-video-ios#128] opened 2020-10-06 16:34 UTC
Hello Mate i have integrate the twilio-video sdk its working fine in start but after some call the call kit provider begin instantly didReset call and call not generate

**Comment by piyushtank** [comment] 2020-10-06 18:12
Can you provide complete information please? you can refer to the template of issue filing.

Also we have a callkit quickstart sample app which might help you solve the problem - https://github.com/twilio/video-quickstart-ios/tree/master/VideoCallKitQuickStart

**Comment by AhmadDurrani579** [comment] 2020-10-06 19:10
Hello Piyush i have already try this but when the CXProvider begin instantly the didreset called its was working fine now i am facing this issue in iOS 14

**Comment by piyushtank** [comment] 2020-10-07 00:06
Please complete the issue format with all details - 


> Before filing an issue please check that the issue is not already addressed by the following:
>
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x)
> 
> If this is an issue with the SDK itself, file it here. If this is an issue with the QuickStart apps, please use [video-quickstart-ios](https://github.com/twilio/video-quickstart-ios/issues).
>
> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

[Description of the issue]

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces How Often

[What percentage of the time does it reproduce?]

#### Logs
Debug level logs are helpful when investigating issues. To enable debug level logging, add the following code to your application:

```.swift
TwilioVideoSDK.setLogLevel(.debug)
```

```
// Log output when the issue occurs
```

### Versions

All relevant version information for the issue.

#### Video iOS SDK

[e.g. 1.3.12 via CocoaPods]

#### Xcode

[e.g. 9.2]

#### iOS Version

[e.g. 11.2.6]

#### iOS Device

[e.g. iPhone 8 Plus]

**Comment by piyushtank** [comment] 2020-10-09 19:05
Closing the ticket due to lack of information. Please reopen the ticket with more information or opened an another one. Thanks.

**Closed as completed by piyushtank** 2020-10-09 19:05 UTC
