### ISSUE TITLE
Video remains paused even after coming back into app from background

### ISSUE THREAD

**Issue by CandiceWright** [twilio/twilio-video-ios#42] opened 2019-04-23 15:08 UTC
### Description

When a user goes to the background while inside of a room, the video pauses as expected for the other user. However, when the user comes back into the app, the video remains paused, but the audio works. I am expecting for the video to start back up automatically. Actually, this behavior was there, and then I updated twilio video to the newest version and it now gives this unexpected behavior.

### Steps to Reproduce

1. Connect two users to a video call
2. Go to the background on one of the devices
3. Return to the foreground and video will remain paused

#### Expected Behavior

I am expecting that the video would automatically resume once the participant returns. Actually, this does happen sometimes, but more often than not, the video just remains paused.

#### Video iOS SDK

2.8.1 via CocoaPods

#### Xcode

v10.2

#### iOS Version

12.2

#### iOS Device

iPhone X and iPad

**Comment by ceaglest** [comment] 2019-04-23 19:28
Hi @CandiceWright,

Thanks for filing an issue. Our upcoming release 2.10.0 has a bug fix related to network handoff, but I am not certain that this is the same issue you are experiencing. Would it be possible to provide a Room SID of a case where media froze upon returning to the foreground?

Alternatively, is the problem reproducible in one of our QuickStart apps?

Best,
Chris

**Comment by ceaglest** [comment] 2019-04-25 00:39
Hi,

I have assigned this issue to @piyushtank, since I will be out of office until Monday. We would like to get to the bottom of this, since video should not remain paused after returning from the background. If you can provide any more info (see my last message) that would be greatly appreciated.

Thanks,
Chris

**Comment by piyushtank** [comment] 2019-05-02 06:16
Hey @CandiceWright 

I tried to reproduce the problem on Quickstart sample app with the steps you have provided using TwilioVideo SDK version `2.10.0`, but I could not reproduce the problem. Video resumed after coming back to foreground. 

In order to debug this problem further, can you provide following information (asked by @ceaglest in previous posts):

- Would it be possible to provide a Room SID of a case where media froze upon returning to the foreground?
- Are you able to reproducible in one of our QuickStart apps?

Best,
Piyush

**Comment by ceaglest** [comment] 2019-06-07 01:05
Hi @CandiceWright,

I didn't see a Room SID, but after re-reading this issue, I believe you are encountering https://github.com/twilio/video-quickstart-swift/issues/388. We are close to deploying a fix for this issue.

Best,
Chris

**Comment by CandiceWright** [comment] 2019-06-18 11:39
Great, Thank you for the follow up!

**Comment by piyushtank** [comment] 2021-01-15 23:18
Closing an old ticket. Feel free to reach out to us if you have any questions.

**Closed as completed by piyushtank** 2021-01-15 23:18 UTC
